import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from "next/font/google";
import { Jura, Rubik, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { Header } from './components/navigation/header'
import { Footer } from './components/navigation/footer'
import { Background } from './components/background/background'

const jura = Jura({
  variable: '--font-jura',
  subsets: ['latin']
})
const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin']
})
const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Tony Cui Website',
  description: 'Generated by create next app'
}

// TODO: uncomment non bg elements when done
export default function RootLayout ({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='en'
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={
        `${jura.variable} ${rubik.variable} ${jetBrainsMono.variable} h-full antialiased`
      }
    >
      <body className='min-h-full flex flex-col'>
        <Background className='fixed w-full h-full -z-10' />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
